### ISSUE TITLE
Documentation for importing other countries' release files

### ISSUE THREAD

**Issue by djbeaumont** [wardle/hermes#26] opened 2021-10-26 20:59 UTC
Hello, I am attempting to use hermes to host the Spanish edition and am running into some trouble. The Spanish download centre lists 3 different files which look like they cover the content I need:
* SnomedCT_International_Edition (I assume necessary as a base for the next two)
* SnomedCT_SpanishRelease-es_PRODUCTION_20210430T120000Z
* SnomedCT_SpainDrugExtension-ES_PRODUCTION_20211001T120000

The first two files import cleanly but the last produces the following output:
```
2021-10-26 20:29:09,822 [main] INFO  com.eldrix.hermes.core - importing  0  distributions from  "/Users/djb/Downloads/SNOMED_CT_SPANISH/SnomedCT_SpainDrugExtension-ES_PRODUCTION_20211001T120000/RF2Release/"
2021-10-26 20:29:09,988 [main] INFO  com.eldrix.hermes.importer - importing files from  "/Users/djb/Downloads/SNOMED_CT_SPANISH/SnomedCT_SpainDrugExtension-ES_PRODUCTION_20211001T120000/RF2Release/"
2021-10-26 20:29:10,002 [async-thread-macro-4] INFO  com.eldrix.hermes.importer - Processing:  "/Users/djb/Downloads/SNOMED_CT_SPANISH/SnomedCT_SpainDrugExtension-ES_PRODUCTION_20211001T120000/RF2Release/Snapshot/Refset/Language/der2_cRefset_LanguageSpainDrugExtensionSnapshot_en_20211001.txt"  type:  "LanguageRefset"
2021-10-26 20:29:10,003 [async-thread-macro-2] INFO  com.eldrix.hermes.importer - Processing:  "/Users/djb/Downloads/SNOMED_CT_SPANISH/SnomedCT_SpainDrugExtension-ES_PRODUCTION_20211001T120000/RF2Release/Snapshot/Refset/Language/der2_cRefset_LanguageSpainDrugExtensionSnapshot_es-ES_ES_20211001.txt"  type:  "LanguageRefset"
2021-10-26 20:29:10,003 [async-thread-macro-1] INFO  com.eldrix.hermes.importer - Processing:  "/Users/djb/Downloads/SNOMED_CT_SPANISH/SnomedCT_SpainDrugExtension-ES_PRODUCTION_20211001T120000/RF2Release/Snapshot/Refset/Content/der2_cRefset_AssociationSpainDrugExtensionSnapshot_es-ES_ES_20211001.txt"  type:  "AssociationRefset"
2021-10-26 20:29:10,002 [async-thread-macro-3] INFO  com.eldrix.hermes.importer - Processing:  "/Users/djb/Downloads/SNOMED_CT_SPANISH/SnomedCT_SpainDrugExtension-ES_PRODUCTION_20211001T120000/RF2Release/Snapshot/Refset/Content/der2_cRefset_AttributeValueSpainDrugExtensionSnapshot_es-ES_ES_20211001.txt"  type:  "AttributeValueRefset"
2021-10-26 20:29:10,005 [async-thread-macro-1] INFO  com.eldrix.hermes.importer - Processing:  "/Users/djb/Downloads/SNOMED_CT_SPANISH/SnomedCT_SpainDrugExtension-ES_PRODUCTION_20211001T120000/RF2Release/Snapshot/Terminology/sct2_Description_SpainDrugExtensionSnapshot_es-ES_ES_20211001.txt"  type:  "Description"
2021-10-26 20:29:10,005 [async-thread-macro-3] INFO  com.eldrix.hermes.importer - Processing:  "/Users/djb/Downloads/SNOMED_CT_SPANISH/SnomedCT_SpainDrugExtension-ES_PRODUCTION_20211001T120000/RF2Release/Snapshot/Terminology/sct2_Concept_SpainDrugExtensionSnapshot_es-ES_ES_20211001.txt"  type:  "Concept"
2021-10-26 20:29:10,059 [async-thread-macro-4] INFO  com.eldrix.hermes.importer - Processing:  "/Users/djb/Downloads/SNOMED_CT_SPANISH/SnomedCT_SpainDrugExtension-ES_PRODUCTION_20211001T120000/RF2Release/Snapshot/Terminology/sct2_Relationship_SpainDrugExtensionSnapshot_es-ES_ES_20211001.txt"  type:  "Relationship"
Exception in thread "async-thread-macro-15" java.lang.NullPointerException
	at com.eldrix.hermes.impl.ser$write_description.invokeStatic(ser.clj:27)
	at com.eldrix.hermes.impl.ser$write_description.invoke(ser.clj:25)
	at com.eldrix.hermes.impl.store$fn__11936$fn__11937.invoke(store.clj:43)
	at com.eldrix.hermes.impl.store.proxy$org.mapdb.serializer.GroupSerializerObjectArray$ff19274a.serialize(Unknown Source)
	at org.mapdb.serializer.GroupSerializerObjectArray.valueArraySerialize(GroupSerializerObjectArray.java:19)
	at com.eldrix.hermes.impl.store.proxy$org.mapdb.serializer.GroupSerializerObjectArray$ff19274a.valueArraySerialize(Unknown Source)
	at org.mapdb.BTreeMapJava$NodeSerializer.serialize(BTreeMapJava.java:171)
	at org.mapdb.BTreeMapJava$NodeSerializer.serialize(BTreeMapJava.java:136)
	at org.mapdb.StoreDirectAbstract.serialize(StoreDirectAbstract.kt:243)
	at org.mapdb.StoreDirect.update(StoreDirect.kt:631)
	at org.mapdb.BTreeMap.put2(BTreeMap.kt:408)
	at org.mapdb.BTreeMap.putIfAbsent(BTreeMap.kt:863)
	at com.eldrix.hermes.impl.store$write_object.invokeStatic(store.clj:127)
	at com.eldrix.hermes.impl.store$write_object.invoke(store.clj:115)
	at com.eldrix.hermes.impl.store$write_object.invokeStatic(store.clj:125)
	at com.eldrix.hermes.impl.store$write_object.invoke(store.clj:115)
	at com.eldrix.hermes.impl.store$write_descriptions.invokeStatic(store.clj:332)
	at com.eldrix.hermes.impl.store$write_descriptions.invoke(store.clj:319)
	at com.eldrix.hermes.impl.store$eval12076$fn__12077.invoke(store.clj:467)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at com.eldrix.hermes.impl.store$write_batch_worker.invokeStatic(store.clj:478)
	at com.eldrix.hermes.impl.store$write_batch_worker.invoke(store.clj:473)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at com.eldrix.hermes.importer$create_workers$fn__14009.invoke(importer.clj:150)
	at clojure.core.async$thread_call$fn__8625.invoke(async.clj:484)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "async-thread-macro-13" java.lang.NullPointerException
	at com.eldrix.hermes.impl.ser$write_language_refset_item.invokeStatic(ser.clj:133)
	at com.eldrix.hermes.impl.ser$write_language_refset_item.invoke(ser.clj:131)
	at com.eldrix.hermes.impl.ser$eval11888$fn__11889.invoke(ser.clj:307)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at com.eldrix.hermes.impl.store$fn__11950$fn__11951.invoke(store.clj:57)
	at com.eldrix.hermes.impl.store.proxy$org.mapdb.serializer.GroupSerializerObjectArray$ff19274a.serialize(Unknown Source)
	at org.mapdb.serializer.GroupSerializerObjectArray.valueArraySerialize(GroupSerializerObjectArray.java:19)
	at com.eldrix.hermes.impl.store.proxy$org.mapdb.serializer.GroupSerializerObjectArray$ff19274a.valueArraySerialize(Unknown Source)
	at org.mapdb.BTreeMapJava$NodeSerializer.serialize(BTreeMapJava.java:171)
	at org.mapdb.BTreeMapJava$NodeSerializer.serialize(BTreeMapJava.java:136)
	at org.mapdb.StoreDirectAbstract.serialize(StoreDirectAbstract.kt:243)
	at org.mapdb.StoreDirect.update(StoreDirect.kt:631)
	at org.mapdb.BTreeMap.put2(BTreeMap.kt:408)
	at org.mapdb.BTreeMap.putIfAbsent(BTreeMap.kt:863)
	at com.eldrix.hermes.impl.store$write_object.invokeStatic(store.clj:127)
	at com.eldrix.hermes.impl.store$write_object.invoke(store.clj:115)
	at com.eldrix.hermes.impl.store$write_object.invokeStatic(store.clj:125)
	at com.eldrix.hermes.impl.store$write_object.invoke(store.clj:115)
	at com.eldrix.hermes.impl.store$write_refset_items.invokeStatic(store.clj:379)
	at com.eldrix.hermes.impl.store$write_refset_items.invoke(store.clj:354)
	at com.eldrix.hermes.impl.store$eval12084$fn__12085.invoke(store.clj:471)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at com.eldrix.hermes.impl.store$write_batch_worker.invokeStatic(store.clj:478)
	at com.eldrix.hermes.impl.store$write_batch_worker.invoke(store.clj:473)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at com.eldrix.hermes.importer$create_workers$fn__14009.invoke(importer.clj:150)
	at clojure.core.async$thread_call$fn__8625.invoke(async.clj:484)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Skipping over that problem for the moment, I tried to continue following the instructions. 
```
 clj -J-Xmx8g -M:run --db snomed.db compact
```
Success!

And now indexing:
```
$ clj -M:run --db snomed.db index

2021-10-26 20:31:33,493 [main] INFO  com.eldrix.hermes.core - Building search index {:root "snomed.db", :languages "en-GB"}
2021-10-26 20:38:28,215 [async-thread-macro-7] WARN  com.eldrix.hermes.impl.search - could not determine preferred synonym for  450828004  using refsets:  (900000000000508004)
2021-10-26 20:38:28,216 [async-thread-macro-7] WARN  com.eldrix.hermes.impl.search - could not determine preferred synonym for  450829007  using refsets:  (900000000000508004)
(Lots and lots of this type of stuff)
```

I noted here that the languages only contains `en-GB` and I haven't been able to find any way of overriding that through a command line argument.

To try and query the Spanish descriptions I have tried the queries from the project readme and variations that seemed like they might work from trying to make sense of the `impl/language.clj` file. Spanish terms can be searched, however, the returned `preferredTerm` is always the English translation:
```
$ curl "http://localhost:8080/v1/snomed/search?s=infarto+mio&maxHits=5" -H "Accept: application/json"  -H "Accept-Language: es-x-448879004" | jq

[
  {
    "id": 898589016,
    "conceptId": 22298006,
    "term": "infarto de miocardio",
    "preferredTerm": "Myocardial infarction"
  },
  {
    "id": 1410692015,
    "conceptId": 164865005,
    "term": "ECG: infarto miocárdico",
    "preferredTerm": "ECG: myocardial infarction"
  },
  {
    "id": 983083013,
    "conceptId": 57054005,
    "term": "infarto agudo de miocardio",
    "preferredTerm": "Acute myocardial infarction"
  },
  {
    "id": 1325180015,
    "conceptId": 233843008,
    "term": "infarto miocárdico silente",
    "preferredTerm": "Silent myocardial infarction"
  },
  {
    "id": 1410695018,
    "conceptId": 164866006,
    "term": "ECG: sin infarto miocárdico",
    "preferredTerm": "ECG: no myocardial infarction"
  }
]
```

How should I negotiate the language or is there another problem here?

**Comment by wardle** [comment] 2021-10-31 09:01
I can reproduce the issue locally. It correctly identifies the files and type of files, but there's something odd happening during serialisation of the description data. I will investigate further.
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/286951/139575375-7b16414e-e0db-44e4-bab7-2af402cfb672.png">

**Comment by wardle** [comment] 2021-10-31 09:18
Hi @djbeaumont - the issue is that the drug release description file has an invalid first row - with a 0 description id and an empty term. 

Now, I think there are two issues for hermes here. The error reporting should be better - for example, if there is an exception during import, the system could output the problem record - and should it continue after identifying invalid data? I have mixed feelings on the latter - that is an issue that needs reporting, and I'd much prefer to fail than ignore invalid data - I think! But I'm open to suggestion. 

The issue of reporting is a bit more complicated than above, because import progresses concurrently in batches of about 5000 items - so just printing out the dodgy batch isn't great. I simply imported at the REPL with a batch size of 1 and added a report. It could be that, after a problem, the system breaks the batch into batches of one, and tries again, and then prints out the dodgy item. It adds a bit of complexity but hermes should provide better error reporting, particularly as in this case it was a problem with the source data, and not my coding!

**Comment by wardle** [comment] 2021-10-31 09:21
I'd suggest we close this issue and open #28

**Comment by wardle** [comment] 2021-10-31 10:21
PS. There looks to be at least one other invalid entry in the spanish drug extension - a language refset item referencing an item 0 -  which obviously is invalid. Surprised this hasn't been picked up by others using SNOMED in Spain, or by other tools, unless they simply ignore invalid data?

**Comment by djbeaumont** [comment] 2021-11-01 12:26
Thanks for finding that bad data. I've taken the approach of pre-filtering the release files in place to get rid of those rows. This seems to be working for me:
```sh
RUN sed -i "/^0.*/d" content/snomed-es-drugs/SnomedCT_SpainDrugExtension-ES_PRODUCTION_20211001T120000/RF2Release/Full/Terminology/sct2_Description_SpainDrugExtensionFull_es-ES_ES_20211001.txt
RUN sed -i "/^0.*/d" content/snomed-es-drugs/SnomedCT_SpainDrugExtension-ES_PRODUCTION_20211001T120000/RF2Release/Snapshot/Terminology/sct2_Description_SpainDrugExtensionSnapshot_es-ES_ES_20211001.txt
RUN sed -i "/^d089af34-d5f8-425b-d478-274c0e1ef550.*/d" content/snomed-es-drugs/SnomedCT_SpainDrugExtension-ES_PRODUCTION_20211001T120000/RF2Release/Full/Refset/Language/der2_cRefset_LanguageSpainDrugExtensionFull_es-ES_ES_20211001.txt
RUN sed -i "/^d089af34-d5f8-425b-d478-274c0e1ef550.*/d" content/snomed-es-drugs/SnomedCT_SpainDrugExtension-ES_PRODUCTION_20211001T120000/RF2Release/Snapshot/Refset/Language/der2_cRefset_LanguageSpainDrugExtensionSnapshot_es-ES_ES_20211001.txt
```
(Exact file paths will depend on your own scripts)

**Comment by djbeaumont** [comment] 2021-11-01 12:30
> So can you try setting --locale to a combination of es reference sets, in priority order. Once we know that is right, I can add that as the default list of refsets to use for es-ES in the helper BCP 47 map.

I'm a bit hazy on how to go about this since I'd have expected the parent concept of `448879004 | Spanish [International Organization for Standardization 639-1 code es] language reference set |` to have been importable but that didn't seem to work.

What should the command line look like with multiple commands? Would it be
```
clj -M:run --db snomed.db index --locale es-x-450828004,es-x-448879004
```

**Comment by djbeaumont** [comment] 2021-11-01 12:34
I think explicitly failing rather than quietly warning is probably the way to go even if implicitly other tools must be skipping over the bad rows as you suggest. At the moment I'm not sure hermes does explicitly fail, since it seems from my builds that it's possible for some errors on workers to stop that worker but the overall manager process reports that the data was successfully imported. I can find a build log if that shouldn't be possible.

**Comment by wardle** [comment] 2021-11-01 16:21
It currently throws an exception but that is in a thread that is not the main thread. So therefore, I catch, log, and re-throw and therefore it becomes an uncaught exception, the thread dies and processing _proceeds_ in the other threads. 

So thank you for spotting.

I either now need to guard against uncaught exceptions using java's Thread/setDefaultUncaughtExceptionHandler, or call System/exit to end prematurely, with the option of continuing if a flag such as --keep-going or --ignore-errors is used.

**Closed** 2021-11-01 21:33 UTC
